### PR TITLE
use cross platform path.sep

### PR DESCRIPTION
**Pull request by junosuarez**
add windows support with goofy directory separators :)

### CODE REVIEW

**Comment by kurttheviking** [comment]
ha; look at you supporting windows now. :+1:

**Comment by junosuarez** [comment]
the things that happen :) fwiw `moquire` (under my gh namespace) also supports windows now, and `minq`'s test suite runs and passes under windows. yak = shaved!

**Comment by kurttheviking** [comment]
awesome; nice work. btw, do you want this repo in your namespace?

**Comment by junosuarez** [comment]
doesn't matter to me - I'm happy to take over maintaining it

**Pull request merged**
